//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Interview()
        {
            this.PanelMembers = new HashSet<PanelMember>();
        }
    
        public int InterviewID { get; set; }
        public int StudentID { get; set; }
        public System.DateTime InterviewDate { get; set; }
        public Nullable<int> SessionID { get; set; }
        public string Room { get; set; }
        public string OverallComment { get; set; }
        public Nullable<decimal> OverallScore { get; set; }
    
        public virtual InterviewSession InterviewSession { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PanelMember> PanelMembers { get; set; }
    }
}
