//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraitCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TraitCategory()
        {
            this.TraitComments = new HashSet<TraitComment>();
        }
    
        public int TraitID { get; set; }
        public string TraitName { get; set; }
        public string TraitDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraitComment> TraitComments { get; set; }
    }
}
